V3.0 dev
esuxiao/mmeta pull request #10
Opened 2022-12-29 23:04 UTC by esuxiao

Create new branch for development of `mmeta V3.0`
Refer to issues:

- #9

2022-12-30 04:52 UTC, esuxiao commented on R/MultipleTables-method-exported.R
> +    MultipleTables._summaryPrint(multiple_tables_object)
Only when verbose == True, the MultipleTables._summaryPrint(multiple_tables_object) function will be called then the cat functions within MultipleTables._summaryPrint() can be called.

2022-12-30 17:58 UTC, jchen1992 requested changes
ggplot2 should be added to imports not depends.

2022-12-31 00:25 UTC, jchen1992 approved these changes

2023-01-01 07:22 UTC, esuxiao commented on DESCRIPTION
> +RoxygenNote: 7.2.2
Try to solve `ERROR: hard-coded installation path: please report to the package maintainer and use '--no-staged-install'` problem. Refer to https://community.rstudio.com/t/no-staged-install-error/35321/2

2023-01-01 07:39 UTC, esuxiao commented on DESCRIPTION
> +StagedInstall: no
Try to solve ERROR: hard-coded installation path: please report to the package maintainer and use '--no-staged-install' problem. Refer to https://community.rstudio.com/t/no-staged-install-error/35321/2

2023-01-19 21:14 UTC, merged

2023-01-19 21:17 UTC, jchen1992 commented
@esuxiao I have merged the V3.0_dev to the main branch. Do you want to delete the V3.0_dev branch?